### ISSUE TITLE
registerInspection() not working in IDEA 2019.2

### ISSUE THREAD

**Issue by kreiger** [dkandalov/live-plugin#102]
java.lang.IllegalStateException: Didn't find any of the fields myInspectionToolFactories,a,b,c  (with class java.util.List) in object com.intellij.codeInspection.ex.InspectionToolRegistrar@50983ed2
    	at liveplugin.implementation.Misc.accessField(Misc.groovy:38)
    	at liveplugin.implementation.Misc$accessField$0.callStatic(Unknown Source)
    	at liveplugin.implementation.Inspections.reloadAdditionalProjectInspections(Inspections.groovy:107)
    	at liveplugin.implementation.Inspections.registerInspection(Inspections.groovy:36)

**Comment by dkandalov** [comment]
Thank you for reporting this. The error is caused by implementation changes in IntelliJ (which caused some of the hacks in liveplugin to break).

You should be able to use `liveplugin.implementation.Inspections.registerInspection2()` function and `unregisterInspection2` though (which don't rely on IJ implementation).

I'll release a new version of liveplugin which will use implementation of `(un)registerInspection2()` functions.
