### ISSUE TITLE
Doesn't work in IDEA 2020.1

### ISSUE THREAD

**Issue by TimReset** [dkandalov/live-plugin#109]
Hi.
It failed with error:
Should be called at least in the state COMPONENTS_REGISTERED, the current state is: LAF_INITIALIZED
Current violators count: 1

java.lang.Throwable
	at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:56)
	at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:52)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:411)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:394)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:20)
	at com.intellij.ide.plugins.PluginUtil.getInstance(PluginUtil.java:11)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:43)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:28)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:36)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:36)
	at com.intellij.notification.NotificationGroup$Companion.balloonGroup(NotificationGroup.kt:60)
	at com.intellij.notification.NotificationGroup.balloonGroup(NotificationGroup.kt)
	at liveplugin.LivePluginAppComponent.<clinit>(LivePluginAppComponent.kt:59)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:288)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:194)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:93)
	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:379)
	at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
	at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:376)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.MainImpl$1.proceed(MainImpl.java:104)
	at com.intellij.ide.b.b.v.proceed(v.java:90)
	at com.intellij.ide.b.b.aQ.b(aQ.java:260)
	at com.intellij.ide.b.b.a7.b(a7.java:276)
	at com.intellij.ide.b.b.a7.c(a7.java:169)
	at com.intellij.ide.b.b.a7.a(a7.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.MainImpl.start(MainImpl.java:96)
	at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:289)
	at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:233)
	at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:45)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by dkandalov** [comment]
Thank you for reporting this. The new version of IJ changed the internal working so I have a few plugins which are broken now :( I'll fix them and upload new version sometime soon.

**Comment by fc1943s** [comment]
Also having problems on startup after updating (2020.2 EAP) =(

**Comment by dkandalov** [comment]
The issue should be fixed in plugin version 0.6.4.

For the record there were two separate issues:
 - in IJ 2020.1 the error "Should be called at least in the state COMPONENTS_REGISTERED, the current state is: LAF_INITIALIZED" on startup, although the plugin still worked fine
 - in IJ 2020.2 the error on startup which made the plugin disabled in IDE

**Comment by fc1943s** [comment]
Everything works after updating. Thank you!

**Comment by TimReset** [comment]
Plugin started but Kotlin plugin can't  be ran:
`Internal error compiling script. java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at liveplugin.pluginrunner.kotlin.KotlinPluginRunner.runPlugin(KotlinPluginRunner.kt:74)
	at liveplugin.pluginrunner.RunPluginActionsKt$runWith$1.invoke(RunPluginActions.kt:89)
	at liveplugin.pluginrunner.RunPluginActionsKt$runWith$1.invoke(RunPluginActions.kt)
	at liveplugin.pluginrunner.BackgroundRunner$SingleThreadBackgroundRunner$run$1$1.run(RunPluginActions.kt:111)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Backend Internal error: Exception during file facade code generationFile being compiled: file://C:/ProgramData/user/.IntelliJIdea/config/plugins/live-plugins/hello-world/plugin.ktsThe root cause java.io.FileNotFoundException was thrown at: java.base/java.io.FileOutputStream.open0(Native Method)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:247)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:78)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:88)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:67)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:634)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyzeAndGenerate(KotlinToJVMBytecodeCompiler.kt:533)
	at liveplugin.pluginrunner.kotlin.compiler.EmbeddedCompilerRunnerKt.compile(EmbeddedCompilerRunner.kt:43)	... 21 more
Caused by: java.io.FileNotFoundException: C:\ProgramData\user\.IntelliJIdea\config\plugins\live-plugins-compiled\LivePlugin(path=C:\ProgramData\user\.IntelliJIdea\config\plugins\live-plugins\hello-world)\Plugin.class (The filename, directory name, or volume label syntax is incorrect)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtil.writeToFile(FileUtil.java:1060)
	at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtil.writeToFile(FileUtil.java:1054)
	at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtil.writeToFile(FileUtil.java:1039)
	at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAll(outputUtils.kt:32)
	at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAllTo(outputUtils.kt:37)
	at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAll(outputUtils.kt:41)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.writeOutput(KotlinToJVMBytecodeCompiler.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.access$writeOutput(KotlinToJVMBytecodeCompiler.kt:81)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$createOutputFilesFlushingCallbackIfPossible$1.invoke(KotlinToJVMBytecodeCompiler.kt:110)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$createOutputFilesFlushingCallbackIfPossible$1.invoke(KotlinToJVMBytecodeCompiler.kt:81)
	at org.jetbrains.kotlin.codegen.state.GenerationStateKt$GenerationStateEventCallback$1.invoke(GenerationState.kt:354)
	at org.jetbrains.kotlin.codegen.state.GenerationStateKt$GenerationStateEventCallback$1.invoke(GenerationState.kt:353)
	at org.jetbrains.kotlin.codegen.state.GenerationState.afterIndependentPart(GenerationState.kt:310)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:71)	... 27 more`

**Comment by dkandalov** [comment]
@TimReset which IDE version specifically you're using? 
(I tried with 201.6668.113 and it was working.)

**Comment by TimReset** [comment]
@dkandalov 
I use the latest stable version for this moment (25 Jun 2020)
IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on June 1, 2020

**Comment by dkandalov** [comment]
I haven't verified it on windows but this should be fixed in plugin version 0.6.7.
