### ISSUE TITLE
does not work in 2020.2

### ISSUE THREAD

**Issue by TimReset** [dkandalov/live-plugin#112]
Hi 
I created PR for 2020.2 https://github.com/dkandalov/live-plugin/pull/111

**Comment by dkandalov** [comment]
Thanks a lot for the PR!
I uploaded new version 0.6.5 to the plugin repository.

**Comment by Gravityzwell** [comment]
Both 064 and 065 lock up Idea 2020.2 for me. I'm staying with 2020.1 as I do want this plugin.

**Comment by dkandalov** [comment]
@Gravityzwell can you give more details please, e.g. does it happen on IDE startup or sometime later?

**Comment by mbwanajm** [comment]
I can't run my plugins on 2020.2.. Used to work on 2020.1
`
<img width="1097" alt="Screenshot 2020-08-04 at 19 09 34" src="https://user-images.githubusercontent.com/369346/89317496-18e76100-d686-11ea-896a-ae0829ae0924.png">
`

**Comment by mbwanajm** [comment]
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at liveplugin.pluginrunner.PluginRunner$ClasspathAddition.createParentClassLoader(PluginRunner.kt:59)
	at liveplugin.pluginrunner.PluginRunner$ClasspathAddition.createClassLoaderWithDependencies(PluginRunner.kt:41)
	at liveplugin.pluginrunner.groovy.GroovyPluginRunner.runGroovyScript(GroovyPluginRunner.kt:41)
	at liveplugin.pluginrunner.groovy.GroovyPluginRunner.runPlugin(GroovyPluginRunner.kt:25)
	at liveplugin.pluginrunner.RunPluginActionsKt$runWith$1.invoke(RunPluginActions.kt:89)
	at liveplugin.pluginrunner.RunPluginActionsKt$runWith$1.invoke(RunPluginActions.kt)
	at liveplugin.pluginrunner.BackgroundRunner$SingleThreadBackgroundRunner$run$1$1.run(RunPluginActions.kt:111)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by dkandalov** [comment]
@mbwanajm I can't reproduce the issue in #IU-202.6397.94, liveplugin 0.6.5.

What is the IDE and plugin version you're using? 
You can find full IDE version in `Main menu -> IntelliJ IDEA -> About IntelliJ IDEA`.

**Comment by mbwanajm** [comment]
@dkandalov seems like we are running the same version.
I realised after updating to the new IntelliJ version all my plugins under LivePlugin disappeared disappeared. 

IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep


LivePlugin:
0.6.5 -beta

**Comment by mbwanajm** [comment]
So I tried something else..
I uninstalled LivePlugin,  and went on to delete all LivePlugin files under /Users/__/Library/Application Support/JetBrains/IntelliJIdea2020.2/plugins
Reinstalled and it worked.!!

**Comment by dkandalov** [comment]
@mbwanajm Glad it works now for you!

I'll release a new version of the plugin which doesn't depend on unstable APIs in IJ and should avoid issues like the one in your stacktrace.

**Comment by Gravityzwell** [comment]
> @Gravityzwell can you give more details please, e.g. does it happen on IDE startup or sometime later?

Idea wouldn't start at all, but it works now. I've done a bunch of things so not sure what the cause was.

**Comment by GorkyCow** [comment]
I have same problem. Plugins reinstallation didn't help

DataGrip 2020.2
Build #DB-202.6397.93, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.5.16-100.fc30.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 4062M
Cores: 4
Non-Bundled Plugins: GrepConsole, LivePlugin
Current Desktop: GNOME

Few days after 0.6.5 releases it worked well but then it stops. Fails on startup

**Comment by mbwanajm** [comment]
My problem came back too :(

**Comment by dkandalov** [comment]
I released version 0.6.6 which should hopefully fix the issue.

@Gravityzwell if Idea still freezes on startup, you can try looking at the IDE thread dumps which are located next to IDE logs in "threadDump" directories. On macOS you can find the log file location from `Main menu -> Help -> Show Log in Finder`. I'm also happy to look into this via screen sharing if it helps.

**Comment by AprilViolet** [comment]
@dkandalov The 0.6.6 version will still freeze the idea, causing the idea to not start

**Comment by dkandalov** [comment]
@AprilViolet @Gravityzwell I think the freeze on startup is related to issue #113. 
I just published version 0.6.7 which should fix this.

**Comment by GorkyCow** [comment]
@dkandalov DataGrip 2020.2.1, Build #DB-202.6948.45, built on August 19, 2020
and LivePlugin 0.6.7.
Looks like it works now. Thanks a lot
