### ISSUE TITLE
Not working on Rider. Potentially a problem with the groovy loader

### ISSUE THREAD

**Issue by fc1943s** [dkandalov/live-plugin#115]
I already tried reinstalling everything. It works on Intellij but not on Rider.
This problem with Rider is happening in only one computer. The plugin works fine on other computers.
Any ideas besides reinstalling Windows? Thanks

Errors:

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:file:/C:/Users/Dell/scoop/apps/rider-eap-portable/current/profile/config/plugins/live-plugins/find-dialog/plugin.groovy: 6: unable to resolve class AnActionEvent @ line 6, column 50.   usFindDialog", "alt shift F") { AnAction                                 ^1 error
	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:311)
```

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:file:/C:/Users/Dell/scoop/apps/rider-eap-portable/current/profile/config/plugins/live-plugins/find-dialog/plugin.groovy: 1: expecting EOF, found 'static' @ line 1, column 9.   ﻿import static liveplugin.PluginUtil.*           ^1 error
	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:311)
```

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:file:/C:/Users/Dell/scoop/apps/rider-eap-portable/current/profile/config/plugins/live-plugins/find-dialog/plugin.groovy: 1: unexpected token: * @ line 1, column 18.   ﻿import java.awt.*                    ^1 error
	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:311)
```

**Comment by dkandalov** [comment]
The errors you posted look like compilation errors.
If you try running examples bundled with liveplugin, do they work?

(Please don't reinstall windows 😅)

**Comment by fc1943s** [comment]
Nop, no groovy code is working. It seems Rider is unable to interpret it at all but is still trying to compile it (Java or Kotlin, maybe?). I tried changing the JVM runtime of Rider to a custom one with the Choose Runtime plugin but no success. Kotlin plugins work, I tried to convert the code but couldn't figure out the right APIs. 
Everything normally works when Rider is installed exactly the same way in my personal machines, which I install myself. This one I started using straight away, I'm suspecting it might be some dll conflict. Already tried reinstalling Rider with and without scoop. I installed Intellij in this machine too and the groovy plugin worked there. Pretty spooky 😂
