### ISSUE TITLE
0.7.6 beta not working with 221.5080.35

### ISSUE THREAD

**Issue by Gribnif** [dkandalov/live-plugin#128]
DataGrip 2022.1 EAP
Build #DB-221.5080.35, built on March 21, 2022

Loading error: ide-actions

com.intellij.diagnostic.PluginException: 
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:Could not instantiate global transform class groovy.grape.GrabAnnotationTransformation specified
at jar:file:/Users/ZZZZZZ/Library/Application%20Support/JetBrains/Toolbox/apps/datagrip/ch-0/221.5080.35/DataGrip%202022.1%20EAP.app/Contents/lib/groovy.jar!/META-INF/services/org.codehaus.groovy.transform.ASTTransformation  because of exception java.lang.ClassNotFoundException: groovy.grape.GrabAnnotationTransformation1 error
	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:295)
	at org.codehaus.groovy.control.ProcessingUnit.completePhase(ProcessingUnit.java:139)
	at org.codehaus.groovy.control.ProcessingUnit.gotoPhase(ProcessingUnit.java:155)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:621)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.doParseClass(GroovyScriptEngine.java:232)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.parseClass(GroovyScriptEngine.java:219)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:257)
	at groovy.util.GroovyScriptEngine.loadScriptByName(GroovyScriptEngine.java:529)
	at liveplugin.pluginrunner.groovy.GroovyPluginRunner.setup(GroovyPluginRunner.kt:50)
	at liveplugin.pluginrunner.RunPluginActionsKt$runWith$1.invoke(RunPluginActions.kt:77)
	at liveplugin.pluginrunner.RunPluginActionsKt.runInBackground$lambda-3(RunPluginActions.kt:93)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829) [Plugin: LivePlugin]
	at liveplugin.IdeUtil.displayError(IdeUtil.kt:55)
	at liveplugin.pluginrunner.RunPluginActionsKt.displayError(RunPluginActions.kt:178)
	at liveplugin.pluginrunner.RunPluginActionsKt.access$displayError(RunPluginActions.kt:1)
	at liveplugin.pluginrunner.RunPluginActionsKt$runWith$1.invoke(RunPluginActions.kt:79)
	at liveplugin.pluginrunner.RunPluginActionsKt.runInBackground$lambda-3(RunPluginActions.kt:93)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by dkandalov** [comment]
Thank you for reporting this!
I haven't verified it in DataGrip 🙈 but I could reproduce it in IntelliJ IDEA (mostly on IDE startup).
Should be fixed in plugin version 0.7.7.
