### ISSUE TITLE
Failed to initialize and will be disabled

### ISSUE THREAD

**Issue by eltonsandre** [dkandalov/live-plugin#131]
Plugin 'LivePlugin' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.IllegalStateException: Could find resource for '/groovy/hello-world/plugin.groovy'.
    at liveplugin.LivePluginAppComponent$Companion.readSampleScriptFile(LivePluginAppComponent.kt:93)
    ...
**environment:**
~~~
IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.14.0-1034-oem
GC: G1 Young Generation, G1 Old Generation
Memory: 3048M
Cores: 8
Kotlin: 221-1.6.20-release-285-IJ5080.210
Current Desktop: X-Cinnamon

~~~

**Plugin version:** 0.6.3 beta
```java
Plugin 'LivePlugin' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.IllegalStateException: Could find resource for '/groovy/hello-world/plugin.groovy'.
    at liveplugin.LivePluginAppComponent$Companion.readSampleScriptFile(LivePluginAppComponent.kt:93)
    at liveplugin.toolwindow.util.ExamplePluginInstaller.installPlugin(ExamplePluginInstaller.kt:14)
    at liveplugin.LivePluginAppComponent$Companion.installHelloWorldPlugins(LivePluginAppComponent.kt:157)
    at liveplugin.LivePluginAppComponent$Companion.access$installHelloWorldPlugins(LivePluginAppComponent.kt:48)
    at liveplugin.LivePluginAppComponent.<init>(LivePluginAppComponent.kt:38)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
    at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:891)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
    at com.intellij.serviceContainer.ComponentManagerImpl$createInitOldComponentsTask$1.run(ComponentManagerImpl.kt:394)
    at com.intellij.idea.ApplicationLoader$prepareStart$1.run(ApplicationLoader.kt:208)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
    at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
    at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
    at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
    at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:393)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by dkandalov** [comment]
Thank you for reporting this!
I wonder why you use plugin version 0.6.3 (which is two years old) with the latest IntelliJ? 🤔 
It's interesting that it fails to find the resource though.

**Comment by eltonsandre** [comment]
Hi @dkandalov 

Very strange as I installed it directly from the IDE's marketplace and this version was installed. A few hours after installing and reporting the issue, the IDE notified an update and installation. Unfortunately now I can't explain why. 🙁
Now I have version 0.7.7 beta, and it works fine! Thank you!

**Comment by dkandalov** [comment]
There used to be some IDE/marketplace bugs related to plugin versions (e.g. Kotlin plugin couldn't upgrade itself). Maybe this is somehow related.
