### ISSUE TITLE
how to depend on this plugin when developing a plugin

### ISSUE THREAD

**Issue by kastork** [dkandalov/live-plugin#160]
I want my plugin to depend on this one, how would I do this?

The jetbrains documentation says to add the plugin id plus a version to the plugins of the intellij configuration. 

https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html

```
intellij {
  plugins.set(listOf("com.example.another-plugin:1.0"))
}
```

I've tried 

"LivePlugin"
"LivePlugin:0.8.6"
"LivePlugin:0.8.6.beta"
"LivePlugin:0.8.6-beta"
"LivePlugin:0.8.6_beta"
"LivePlugin:0.8.6beta"

My main goal here is to have LivePlugin be available to the sandbox IDE you get when running the "runIde" gradle target (I'm basing my project on the plugin template project).

**Comment by dkandalov** [comment]
From what I can see in the documentation "LivePlugin" should just work but I get
> Cannot find builtin plugin 'LivePlugin' for IDE: ...

No idea why it's not searching non-bundled plugins.
Maybe it's a bug in gradle-intellij-plugin 🤷🤔

**Comment by mrolappe** [comment]
@kastork Have you tried using the version verbatim as listed on the plugin page? For instance, "LivePlugin:0.7.5 beta", i.e. including whitespace, works for me.

**Comment by kastork** [comment]
No, but I will

**Comment by kastork** [comment]
@mrolappe Thank you.

This does indeed get the plugin to be active in the sandbox IDE.

Here's my buildfile `intellij` block

```kotlin
intellij {
    pluginName.set(properties("pluginName"))
    version.set(properties("platformVersion"))
    type.set(properties("platformType"))

    // Plugin Dependencies. Uses `platformPlugins` property from the gradle.properties file.
    val bundled = properties("platformPlugins")
        .split(',')
        .map(String::trim)
        .filter(String::isNotEmpty)
        .toMutableList()

    val unbundled = listOf<String>(
        "LivePlugin:0.7.5 beta"
    )

    plugins.set(bundled + unbundled)
}
```

However, when I add the built in example groovy Hello World, I get...

```bash
Error linking script. 'void com.intellij.util.lang.UrlClassLoader.<init>(com.intellij.util.lang.UrlClassLoader$Builder, java.util.function.Function, boolean, boolean)'
```

If I try the kotlin Hello World, I get:

```bash
Error while loading plugin class.
java.lang.NoSuchMethodError: 'void com.intellij.util.lang.UrlClassLoader.<init>(com.intellij.util.lang.UrlClassLoader$Builder, java.util.function.Function, boolean, boolean)'
	at liveplugin.pluginrunner.PluginClassLoader_Fork.<init>(PluginClassLoader_Fork.java:132)
	at liveplugin.pluginrunner.PluginRunner$ClasspathAddition.createParentClassLoader(PluginRunner.kt:49)
	at liveplugin.pluginrunner.PluginRunner$ClasspathAddition.createClassLoaderWithDependencies(PluginRunner.kt:37)
	at liveplugin.pluginrunner.kotlin.KotlinPluginRunner.setup(KotlinPluginRunner.kt:79)
	at liveplugin.pluginrunner.RunPluginActionsKt$runWith$1.invoke(RunPluginActions.kt:77)
	at liveplugin.pluginrunner.RunPluginActionsKt$runInBackground$2.run(RunPluginActions.kt:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Maybe I'm missing some other plugin dependency??

**Comment by dkandalov** [comment]
@kastork these exceptions look to me like LivePlugin:0.7.5 beta is not compatible with the IDE version you're running in sandbox. In particular, UrlClassLoader is binary incompatible with the plugin version.

**Comment by kastork** [comment]
Yes, that was it.

Oddly, If I try 0.8.6 beta, the gradle sync fails with an incompatibility notice,  0.8.0 syncs fine and then also seems to work fine in the sandbox as well.

Thanks to you both for the help.
