### ISSUE TITLE
Error while loading plugin class in com.intellij.util.lang.UrlClassLoader.loadClassInsideSelf

### ISSUE THREAD

**Issue by foto-andreas** [dkandalov/live-plugin#191]
Hi,

I am using IntelliJ Ultimate 2024.3 and LivePlugin 0.9.3 beta. I constantly geting the following error (with stacktrace in kotlin, without stacktrace in groovy) when trying the sample plugins:

```
Error while loading plugin class.
com.intellij.diagnostic.PluginException: Cannot load class Plugin (  error: 'java.lang.Class com.intellij.util.lang.UrlClassLoader.loadClassInsideSelf(java.lang.String, java.lang.String, long, boolean)',  classLoader=PluginClassLoader_Fork(plugin=Default plugin descriptor for show, packagePrefix=null, instanceId=13, state=active)) [Plugin: show]
	at liveplugin.implementation.pluginrunner.PluginClassLoader_Fork.loadClassInsideSelf(PluginClassLoader_Fork.java:447)
	at liveplugin.implementation.pluginrunner.PluginClassLoader_Fork.tryLoadingClass(PluginClassLoader_Fork.java:257)
	at liveplugin.implementation.pluginrunner.PluginClassLoader_Fork.loadClass(PluginClassLoader_Fork.java:229)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at liveplugin.implementation.pluginrunner.kotlin.KotlinPluginRunner.setup(KotlinPluginRunner.kt:84)
	at liveplugin.implementation.pluginrunner.PluginRunnerKt$runWith$1.invoke(PluginRunner.kt:161)
	at liveplugin.implementation.pluginrunner.PluginRunnerKt$runInBackground$2.run(PluginRunner.kt:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NoSuchMethodError: 'java.lang.Class com.intellij.util.lang.UrlClassLoader.loadClassInsideSelf(java.lang.String, java.lang.String, long, boolean)'
	at liveplugin.implementation.pluginrunner.PluginClassLoader_Fork.tryLoadingClass(PluginClassLoader_Fork.java:308)
	at liveplugin.implementation.pluginrunner.PluginClassLoader_Fork.loadClass(PluginClassLoader_Fork.java:229)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:297)
	at com.intellij.util.lang.FileLoader.findClass(FileLoader.java:187)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:240)
	at com.intellij.util.lang.ClassPath.findClassWithoutCache(ClassPath.java:229)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:212)
	at liveplugin.implementation.pluginrunner.PluginClassLoader_Fork.loadClassInsideSelf(PluginClassLoader_Fork.java:439)	... 36 more
```

Andreas

**Comment by dkandalov** [comment]
This should be fixed in version 0.9.4 (once approve by JetBrains).

Sorry about the failures, it happens because of incompatible API changes in IntelliJ and this plugin has to depend on some classes which are not part of the public API :(

**Comment by foto-andreas** [comment]
fixed. nice. thank you. in 2024.2 the plugin-update is not visible?

**Comment by foto-andreas** [comment]
works as expected
