### ISSUE TITLE
No errors are displayed when evaluating plugin with 'final' field being reassigned

### ISSUE THREAD

**Issue by dkandalov** [dkandalov/live-plugin#30]
(Noticed in code-history-mining events.csv4180.CSVReader)

**Comment by dkandalov** [comment]
Cannot reproduce. This code fails and shows error as expected:
```groovy
class Final {
    final int i
    Final(int i) {
        this.i = i
    }
}
def f = new Final(123)
f.i = 2

show("hello")
```

Output:
```
groovy.lang.ReadOnlyPropertyException: Cannot set readonly property: i for class: Final
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2681)
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3702)
	at Final.setProperty(plugin.groovy)
	at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:191)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:482)
	at plugin.run(plugin.groovy:26)
	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:577)
	at liveplugin.pluginrunner.GroovyPluginRunner$2.run(GroovyPluginRunner.java:89)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```
