### ISSUE TITLE
"cannot share data context between Swing events"

### ISSUE THREAD

**Issue by dkandalov** [dkandalov/live-plugin#37]
cannot share data context between Swing events; initial event count = 309074; current event count = 309212
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:342)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:75)
	at com.intellij.openapi.actionSystem.AnActionEvent.getData(AnActionEvent.java:140)
	at com.intellij.openapi.actionSystem.AnActionEvent.getProject(AnActionEvent.java:96)
	at liveplugin.pluginrunner.RunPluginAction.pluginsSelectedInToolWindow(RunPluginAction.java:156)
	at liveplugin.pluginrunner.RunPluginAction.findCurrentPluginIds(RunPluginAction.java:142)
	at liveplugin.pluginrunner.TestPluginAction.testCurrentPlugin(TestPluginAction.java:40)
	at liveplugin.pluginrunner.TestPluginAction.actionPerformed(TestPluginAction.java:31)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.b(IdeKeyEventDispatcher.java:342)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:281)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:494)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by irfaan008** [comment]
Any update on this issue?

**Comment by dkandalov** [comment]
Not really. I never had this problem again in day to day usage.
I'm going to release new version of the plugin soon and will look into this problem.
Thanks a lot for reminding.

**Comment by dkandalov** [comment]
Do you know how to reproduce this issue?
I can't reproduce this exception anymore and IntelliJ api which used to show refresh from file system dialog has changed.

**Comment by irfaan008** [comment]
If I will try to import the library folder of the project to my project as an existing module then I get this error.

**Comment by dkandalov** [comment]
Hm.. not sure what you mean by "import the library folder of the project ... as an existing module". 
May be "Add LivePlugin Jar to Project" action?

**Comment by irfaan008** [comment]
Ok my mistake. I don't know how I landed to this page and started this conversation on this thread. Actually I was trying to import this project https://github.com/navasmdc/MaterialDesignLibrary

and on importing I got this error. I am not sure if its related to intelliJ or the project mentioned above.

**Comment by dkandalov** [comment]
No problem :) 
In the right bottom corner of main window there should be exclamation mark icon. After clicking on it, it should open "IDE internal errors" window which at the top says something like "Exception in IDEA core".
If it doesn't say "Exception in LivePlugin", then it's probably not related to this plugin.

**Comment by 3363686** [comment]
Dmitry, I get this error while inserting one liveplugin example into another one (popupMenu):

registerAction("HelloTextEditorAction", keyHello) { AnActionEvent event ->
  runDocumentWriteAction(event.project) {
    def editor = currentEditorIn(event.project)
    editor.document.text += "\nHello IntelliJ"
  }
}

works fine and silent, while

registerAction( aid, key ){
  AnActionEvent event ->
    def popupMenuContent = [
      "Hello":{
        runDocumentWriteAction(event.project) {
          def editor = currentEditorIn(event.project)
          editor.document.text += "\nHello IntelliJ"
        }
      },
.........

- works fine but produces "Throwable: cannot share data context between Swing events; initial event count = 310158; current event count = 310272".
Another tries to modify editor content, being called from within menu, make the same exception, and this is stable.

**Comment by dkandalov** [comment]
Hello,

This is because IntelliJ API doesn't allow sharing ```AnActionEvent```s between swing events.
In your example one swing event is to show popup menu and another swing event is clicking on popup menu item. The problem is that you use ```event.project``` where ```event``` comes from the first swing event. The simplest fix is to save reference to project before showing popup menu.

I just updated popup menu example to use current project https://github.com/dkandalov/live-plugin/blob/master/plugin_examples/liveplugin/pluginexamples/actionsPopupMenu/plugin.groovy
Thanks a lot for pointing this out!

(Btw, although the error looks very similar it's not really related to this issue.)

**Comment by 3363686** [comment]
Dmitry, great thanks for your explanation -- all is OK now! -- and for your plugin itself. I'm full newbie in all this things, but LivePlugin gives the very convenient entry point to start, thank you!

Alexei
