### ISSUE TITLE
Error when deleting plugin

### ISSUE THREAD

**Issue by dkandalov** [dkandalov/live-plugin#5]
(on windows)
- create plugin
- make it register an action
- evaluate plugin
- run plugin
- deleting plugin fails with the following exception

``` java
Cannot delete file C:\Users\...\.IntelliJIdea12\config\plugins\intellij-eval-plugins\aaaa\plugin.groovy.: Cannot delete file C:\Users\...\.IntelliJIdea12\config\plugins\intellij-eval-plugins\aaaa\plugin.groovy.
java.io.IOException: Cannot delete file C:\Users\...\.IntelliJIdea12\config\plugins\intellij-eval-plugins\aaaa\plugin.groovy.
    at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.a(LocalFileSystemBase.java:377)
    at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.a(LocalFileSystemBase.java:372)
    at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.deleteFile(LocalFileSystemBase.java:419)
    at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.deleteFile(PersistentFSImpl.java:461)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.delete(VirtualFileSystemEntry.java:289)
    at intellijeval.toolwindow.PluginToolWindowManager$PluginsIO$3.run(PluginToolWindowManager.java:951)
    at intellijeval.toolwindow.PluginToolWindowManager$PluginsIO$4$1.run(PluginToolWindowManager.java:965)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:986)
    at intellijeval.toolwindow.PluginToolWindowManager$PluginsIO$4.run(PluginToolWindowManager.java:961)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:122)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:97)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:83)
    at intellijeval.toolwindow.PluginToolWindowManager$PluginsIO.runIOAction(PluginToolWindowManager.java:959)
    at intellijeval.toolwindow.PluginToolWindowManager$PluginsIO.delete(PluginToolWindowManager.java:945)
    at intellijeval.toolwindow.PluginToolWindowManager$DeletePluginAction.actionPerformed(PluginToolWindowManager.java:661)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:169)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:132)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:310)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:682)
    at java.awt.EventQueue$3.run(EventQueue.java:680)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:696)
    at java.awt.EventQueue$4.run(EventQueue.java:694)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:693)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:673)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:494)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:333)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)
```

**Comment by dkandalov** [comment]
Haven't seen this problem for ages, so it's most likely out-of-date now.
