### ISSUE TITLE
Question about the `inspect` method.

### ISSUE THREAD

**Issue by aristotll** [dkandalov/live-plugin#71]
I have the following code:
```groovy
registerAction("LPInspectObject", "ctrl shift 9") { AnActionEvent event ->
    show("loaded")
    inspect("loaded")
    inspect(event.project)
    inspect(event)
}

if (!isIdeStartup) show("Plugin Loaded")

```
The strange things is the first two inspections works, but the last one `inspect(event)` does **not** show anything.

**Comment by dkandalov** [comment]
Hello,

Thanks a lot for reporting this!
I'll fix `inspect` method in the next version of the plugin.
As a workaround you can try and paste [this code of fixed ObjectInspector](https://github.com/dkandalov/live-plugin/blob/2948664b8f4837a1ad4a03b0f4f2ac7855945e18/src_groovy/liveplugin/implementation/ObjectInspector.groovy) into `plugin.groovy` and use it as `ObjectInspector.showPopup(event)`.

Overall, it looks like the issue is caused by exception while trying to convert of the fields of `event` object to string. After running `inspect(event)` there should be red circle blinking in the bottom right of IDE frame. If you click on it, it should have something like this:
```
method not implemented
java.lang.RuntimeException: method not implemented
	at com.intellij.util.containers.RefValueHashMap.entrySet(RefValueHashMap.java:133)
	at com.intellij.util.containers.WeakValueHashMap.entrySet(WeakValueHashMap.java:24)
	at org.codehaus.groovy.runtime.InvokerHelper.formatMap(InvokerHelper.java:647)
	at org.codehaus.groovy.runtime.InvokerHelper.toMapString(InvokerHelper.java:752)
	at org.codehaus.groovy.runtime.InvokerHelper.toMapString(InvokerHelper.java:741)
	at org.codehaus.groovy.runtime.InvokerHelper.toString(InvokerHelper.java:129)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.toString(DefaultGroovyMethods.java:13691)
	at org.codehaus.groovy.runtime.dgm$707.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at java_lang_Integer$toString.call(Unknown Source)
	at liveplugin.implementation.ObjectInspector.presentationOf(ObjectInspector.groovy:75)
```
And it makes sense because `RefValueHashMap` really doesn't implement this method (see [source code](https://github.com/JetBrains/intellij-community/blob/10f7df6ea9685aa7e82e89fe13325988ee383b64/platform/util/src/com/intellij/util/containers/RefValueHashMap.java#L133)).
