### ISSUE TITLE
depends on Python plugin problem

### ISSUE THREAD

**Issue by aristotll** [dkandalov/live-plugin#72]
I see https://github.com/dkandalov/live-plugin/pull/45

I just want to know if `python` plugin is supported.

I used  `// depends-on-plugin com.intellij.modules.python` according to http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html

But it just did  not work.

```log
Couldn't load plugin: "inspection_py". Couldn't find dependent plugin 'com.intellij.modules.python'Couldn't load plugin: "inspection_py". org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:file:/Users/.../Library/Application%20Support/IntelliJIdea2017.1/live-plugins/inspection_py/plugin.groovy: 6: unable to resolve class com.jetbrains.python.inspections.PyInspection @ line 6, column 1.   import com.jetbrains.python.inspections.PyInspection   ^file:/Users/Yao/Library/Application%20Support/IntelliJIdea2017.1/live-plugins/inspection_py/plugin.groovy: 7: unable to resolve class com.jetbrains.python.inspections.PyInspectionVisitor @ line 7, column 1.   import com.jetbrains.python.inspections.PyInspectionVisitor   ^file:/Users/Yao/Library/Application%20Support/IntelliJIdea2017.1/live-plugins/inspection_py/plugin.groovy: 9: unable to resolve class com.jetbrains.python.psi.PyExpression @ line 9, column 1.   import com.jetbrains.python.psi.PyExpression   ^file:/Users/Yao/Library/Application%20Support/IntelliJIdea2017.1/live-plugins/inspection_py/plugin.groovy: 8: unable to resolve class com.jetbrains.python.psi.PyAssignmentStatement @ line 8, column 1.   import com.jetbrains.python.psi.PyAssignmentStatement   ^4 errors
	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:946)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:593)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:542)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.doParseClass(GroovyScriptEngine.java:256)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.parseClass(GroovyScriptEngine.java:243)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:254)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:212)
	at groovy.util.GroovyScriptEngine.loadScriptByName(GroovyScriptEngine.java:566)
	at liveplugin.pluginrunner.GroovyPluginRunner.runGroovyScript(GroovyPluginRunner.java:78)
	at liveplugin.pluginrunner.GroovyPluginRunner.runPlugin(GroovyPluginRunner.java:53)
	at liveplugin.pluginrunner.RunPluginAction.lambda$runPlugins$48(RunPluginAction.java:104)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dkandalov** [comment]
I just tried and can confirm there is a problem with depending on python plugin.
In theory it should work though. I'll try to look into it later today.

**Comment by aristotll** [comment]
Ok I look into the source code and write 
```groovy
        def rawPluginId = 'Pythonid'
//        def rawPluginId = 'org.intellij.scala'
        PluginId pluginId = PluginId.getId(rawPluginId);
        IdeaPluginDescriptor pluginDescriptor = PluginManager.getPlugin(pluginId);
        inspect(pluginDescriptor)
```

By searching the `Python.jar`and the id is `Pythonid`
```xml
 <id>Pythonid</id>
  <idea-version since-build="171.4694" until-build="171.*"/>
  <version>2017.1.171.4694.26</version>
  <name>Python</name>

  <description><![CDATA[
The Python plug-in provides smart editing for Python scripts. The feature set of the plugin
 corresponds to PyCharm IDE Professional Edition.
<br>
<a href="http://blog.jetbrains.com/pycharm">PyCharm blog</a><br>
<a href="http://forum.jetbrains.com/forum/PyCharm">Discussion forum</a><br>
<a href="https://youtrack.jetbrains.com/issues/PY">Issue tracker</a><br>
]]></description>
```

```
// depends-on-plugin Pythonid
```
And It works

**Comment by aristotll** [comment]
I write something like https://gist.github.com/aristotll/1f6e440b8f6cb30f36db9fd2e71a4be3

I turns out that the names are not all in same conventions.

**Comment by dkandalov** [comment]
Cool, thanks for sharing this :)
 
This is similar to what I wanted to understand yesterday (but didn't get to do it), why `PluginId.getId("com.intellij.modules.python")` returns id but then `PluginManager.getPlugin()` returns `null`.
