### ISSUE TITLE
No such property: MyExtensionPointManager for class: com.intellij.codeInsight.completion.CompletionContributor

### ISSUE THREAD

**Issue by aristotll** [dkandalov/live-plugin#73]
I try to execute the code from https://github.com/dkandalov/live-plugin/wiki/Google-auto-complete

But 
```
groovy.lang.MissingPropertyException: No such property: MyExtensionPointManager for class: com.intellij.codeInsight.completion.CompletionContributor
	at groovy.lang.MetaClassImpl.invokeStaticMissingProperty(MetaClassImpl.java:1001)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1856)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1832)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3734)
	at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.getProperty(ClassMetaClassGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
	at plugin.resetCompletionContributorCache(plugin.groovy:68)
	at plugin.registerCompletionContributor(plugin.groovy:50)
	at plugin$registerCompletionContributor.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:230)
	at plugin.run(plugin.groovy:37)
	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:603)
	at liveplugin.pluginrunner.GroovyPluginRunner.lambda$runGroovyScript$18(GroovyPluginRunner.java:86)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by dkandalov** [comment]
I think the gist is fixed now (sorry for such a late reply 😨)
