### ISSUE TITLE
Plugin does not run on PhpStorm 2018.2 

### ISSUE THREAD

**Issue by Cosmologist** [dkandalov/live-plugin#86]
I install plugin v0.6.1 beta through Settings -> Plugins, but after every launch i have a message:
```
com.intellij.diagnostic.PluginException: java.lang.reflect.InvocationTargetException [Plugin: LivePlugin]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:144)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:458)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:446)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1266)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:226)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:199)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:160)
	at com.intellij.util.ReflectionUtil.createAsDataClass(ReflectionUtil.java:489)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:422)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:141)
	... 19 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.util.ReflectionUtil.createAsDataClass(ReflectionUtil.java:465)
	... 21 more
Caused by: java.lang.NoClassDefFoundError: org/jetbrains/kotlin/codegen/CompilationException
	at liveplugin.toolwindow.addplugin.AddNewKotlinPluginAction.<init>(AddNewPluginAction.kt:29)
	... 26 more
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.codegen.CompilationException PluginClassLoader[LivePlugin, 0.6.1 beta] com.intellij.ide.plugins.cl.PluginClassLoader@41ec234f
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more

```

I try to install the lastest version (v0.6.2beta), but I get a message about the incompatibility of the plug-in with the IDE version.
IDE: PhpStorm 2018.2 

How i can install it?

**Comment by dkandalov** [comment]
This was fixed in v0.6.3 and should be working starting from PhpStorm 2019.1.

I check it in
```
PhpStorm 2019.1.2
Build #PS-191.7141.52, built on May 8, 2019
JRE: 1.8.0_202-release-1483-b49 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
```

Sorry it took ages to look into the issue :(
