### ISSUE TITLE
Clone from gist doesn't work

### ISSUE THREAD

**Issue by markusmo3** [dkandalov/live-plugin#87]
If i try to use the "Clone from gist" feature i get an error.

used gist url: https://gist.github.com/dkandalov/277800d12ecbfc533fcd
error in idea.log:
```2018-10-23 14:11:11,989 [21760392]   INFO - in.git.AddPluginFromGistAction - URI does not specify a valid host name: https:///api/v3/gists/277800d12ecbfc533fcd 
org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: https:///api/v3/gists/277800d12ecbfc533fcd
	at org.apache.http.impl.client.CloseableHttpClient.determineTarget(CloseableHttpClient.java:95)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.jetbrains.plugins.github.api.GithubConnection.doREST(GithubConnection.java:248)
	at org.jetbrains.plugins.github.api.GithubConnection.doRequest(GithubConnection.java:151)
	at org.jetbrains.plugins.github.api.GithubConnection.request(GithubConnection.java:135)
	at org.jetbrains.plugins.github.api.GithubConnection.getRequest(GithubConnection.java:75)
	at org.jetbrains.plugins.github.api.GithubApiUtil.load(GithubApiUtil.java:93)
	at org.jetbrains.plugins.github.api.GithubApiUtil.getGist(GithubApiUtil.java:353)
	at liveplugin.toolwindow.addplugin.git.AddPluginFromGistAction$2.run(AddPluginFromGistAction.java:83)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-10-23 14:12:05,640 [21814043]   INFO - in.git.AddPluginFromGistAction - URI does not specify a valid host name: https:///api/v3/gists/277800d12ecbfc533fcd 
org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: https:///api/v3/gists/277800d12ecbfc533fcd
	at org.apache.http.impl.client.CloseableHttpClient.determineTarget(CloseableHttpClient.java:95)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.jetbrains.plugins.github.api.GithubConnection.doREST(GithubConnection.java:248)
	at org.jetbrains.plugins.github.api.GithubConnection.doRequest(GithubConnection.java:151)
	at org.jetbrains.plugins.github.api.GithubConnection.request(GithubConnection.java:135)
	at org.jetbrains.plugins.github.api.GithubConnection.getRequest(GithubConnection.java:75)
	at org.jetbrains.plugins.github.api.GithubApiUtil.load(GithubApiUtil.java:93)
	at org.jetbrains.plugins.github.api.GithubApiUtil.getGist(GithubApiUtil.java:353)
	at liveplugin.toolwindow.addplugin.git.AddPluginFromGistAction$2.run(AddPluginFromGistAction.java:83)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by dkandalov** [comment]
This is fixed in v0.6.3 (also the action was renamed to "Copy from gist").

Sorry it took ages to fix the issue (it stopped working at some point because of changes in IJ api).
