### ISSUE TITLE
Kotlin Examples not working

### ISSUE THREAD

**Issue by humazed** [dkandalov/live-plugin#92]
I'm trying to run kotlin hello world example but I'm getting this error.
note that groovy works fine

`Couldn't load plugin: "hello-world". Internal error compiling script. java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at liveplugin.pluginrunner.kotlin.KotlinPluginRunner.runPlugin(KotlinPluginRunner.kt:95)
	at liveplugin.pluginrunner.RunPluginActionKt$runPlugins$$inlined$map$lambda$1.invoke(RunPluginAction.kt:95)
	at liveplugin.pluginrunner.RunPluginActionKt$runPlugins$$inlined$map$lambda$1.invoke(RunPluginAction.kt)
	at liveplugin.IdeUtilKt$sam$Runnable$c70d6208.run(IdeUtil.kt)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't transform method node: <init> (Lcom/intellij/openapi/project/Project;ZLjava/lang/String;Lcom/intellij/openapi/Disposable;)V:    ALOAD 0    ALOAD 1    ILOAD 2    ALOAD 3    ALOAD 4    INVOKESPECIAL liveplugin/pluginrunner/kotlin/KotlinScriptTemplate.<init> (Lcom/intellij/openapi/project/Project;ZLjava/lang/String;Lcom/intellij/openapi/Disposable;)V    ALOAD 0   L0    LINENUMBER 10 L0    LDC "Hello world"    ACONST_NULL    ACONST_NULL    ACONST_NULL    ACONST_NULL    BIPUSH 30    ACONST_NULL    INVOKESTATIC liveplugin/Plugin_utilKt.show$default (Ljava/lang/Object;Ljava/lang/String;Lcom/intellij/notification/NotificationType;Ljava/lang/String;Lcom/intellij/notification/NotificationListener;ILjava/lang/Object;)V    RETURN    MAXSTACK = 8    MAXLOCALS = 5Cause: java.lang.IllegalStateExceptionElement is unknownThe root cause was thrown at: SourceInterpreter.java:56
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.java:88)
	at org.jetbrains.kotlin.codegen.ScriptCodegen.genConstructor(ScriptCodegen.java:212)
	at org.jetbrains.kotlin.codegen.ScriptCodegen.generateBody(ScriptCodegen.java:103)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:137)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:120)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:66)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.generatePackage(KotlinCodegenFacade.java:99)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:77)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:44)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:442)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyzeAndGenerate(KotlinToJVMBytecodeCompiler.kt:359)
	at liveplugin.pluginrunner.kotlin.compiler.EmbeddedCompilerRunnerKt.compilePlugin(EmbeddedCompilerRunner.kt:33)	... 13 more
Caused by: java.lang.IllegalStateException
	at org.jetbrains.org.objectweb.asm.tree.analysis.SourceInterpreter.<init>(SourceInterpreter.java:56)
	at org.jetbrains.kotlin.codegen.optimization.boxing.PopBackwardPropagationTransformer$Transformer$analyzeMethodBody$1.<init>(PopBackwardPropagationTransformer.kt:78)
	at org.jetbrains.kotlin.codegen.optimization.boxing.PopBackwardPropagationTransformer$Transformer.analyzeMethodBody(PopBackwardPropagationTransformer.kt:78)
	at org.jetbrains.kotlin.codegen.optimization.boxing.PopBackwardPropagationTransformer$Transformer.access$analyzeMethodBody(PopBackwardPropagationTransformer.kt:39)
	at org.jetbrains.kotlin.codegen.optimization.boxing.PopBackwardPropagationTransformer$Transformer$frames$2.invoke(PopBackwardPropagationTransformer.kt:65)
	at org.jetbrains.kotlin.codegen.optimization.boxing.PopBackwardPropagationTransformer$Transformer$frames$2.invoke(PopBackwardPropagationTransformer.kt:39)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.codegen.optimization.boxing.PopBackwardPropagationTransformer$Transformer.getFrames(PopBackwardPropagationTransformer.kt)
	at org.jetbrains.kotlin.codegen.optimization.boxing.PopBackwardPropagationTransformer$Transformer.computeTransformations(PopBackwardPropagationTransformer.kt:123)
	at org.jetbrains.kotlin.codegen.optimization.boxing.PopBackwardPropagationTransformer$Transformer.transform(PopBackwardPropagationTransformer.kt:70)
	at org.jetbrains.kotlin.codegen.optimization.boxing.PopBackwardPropagationTransformer.transform(PopBackwardPropagationTransformer.kt:36)
	at org.jetbrains.kotlin.codegen.optimization.transformer.CompositeMethodTransformer.transform(CompositeMethodTransformer.kt:23)
	at org.jetbrains.kotlin.codegen.optimization.OptimizationMethodVisitor.performTransformations(OptimizationMethodVisitor.kt:42)
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.java:65)	... 24 more
Couldn't load plugin: "hello-world". Didn't find plugin dependency 'C:\Users\huma\.AndroidStudio3.4\config\plugins\live-plugins-classes\hello-world'.
Couldn't load plugin: "hello-world". Error while loading plugin class. java.lang.ClassNotFoundException: Plugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:702)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:812)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:800)
	at liveplugin.pluginrunner.kotlin.KotlinPluginRunner.runPlugin(KotlinPluginRunner.kt:121)
	at liveplugin.pluginrunner.RunPluginActionKt$runPlugins$$inlined$map$lambda$1.invoke(RunPluginAction.kt:95)
	at liveplugin.pluginrunner.RunPluginActionKt$runPlugins$$inlined$map$lambda$1.invoke(RunPluginAction.kt)
	at liveplugin.IdeUtilKt$sam$Runnable$c70d6208.run(IdeUtil.kt)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by dkandalov** [comment]
Yes, sorry. Kotlin is changing too fast and its support in the plugin is a bit of a hack.
I'm going to fix this in the next version.

**Comment by dkandalov** [comment]
This was fixed in v0.6.3 and should be working starting from IntelliJ 2019.1.
