### ISSUE TITLE
Notification group Live Plugin is already registered 

### ISSUE THREAD

**Issue by krasa** [dkandalov/live-plugin#99]
NotificationGroup instance should be a static final field.

```
2019-06-19 11:42:18,318 [ 850296]   INFO - notification.NotificationGroup - Notification group Live Plugin is already registered 
java.lang.Throwable
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:65)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:50)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:43)
	at com.intellij.notification.NotificationGroup.balloonGroup(NotificationGroup.java:72)
	at liveplugin.LivePluginAppComponent.<clinit>(LivePluginAppComponent.kt:59)
	at liveplugin.pluginrunner.kotlin.LivePluginScriptCompilationConfiguration$1.invoke(LivePluginScriptCompilationConfiguration.kt:10)
	at liveplugin.pluginrunner.kotlin.LivePluginScriptCompilationConfiguration$1.invoke(LivePluginScriptCompilationConfiguration.kt:9)
	at kotlin.script.experimental.api.ScriptCompilationConfiguration.<init>(scriptCompilation.kt:21)
	at kotlin.script.experimental.api.ScriptCompilationConfiguration.<init>(scriptCompilation.kt:23)
	at liveplugin.pluginrunner.kotlin.LivePluginScriptCompilationConfiguration.<init>(LivePluginScriptCompilationConfiguration.kt:9)
	at liveplugin.pluginrunner.kotlin.LivePluginScriptCompilationConfiguration.<clinit>(LivePluginScriptCompilationConfiguration.kt:9)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:114)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:62)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt)
	at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:239)
	at kotlin.script.experimental.host.ConfigurationFromTemplateKt$createCompilationConfigurationFromTemplate$2.invoke(configurationFromTemplate.kt:61)
	at kotlin.script.experimental.host.ConfigurationFromTemplateKt.createCompilationConfigurationFromTemplate(configurationFromTemplate.kt:66)
	at kotlin.script.experimental.host.ConfigurationFromTemplateKt.createCompilationConfigurationFromTemplate$default(configurationFromTemplate.kt:33)
	at org.jetbrains.kotlin.idea.core.script.ScriptDefinitionsManagerKt.loadDefinitionsFromTemplates(ScriptDefinitionsManager.kt:255)
	at org.jetbrains.kotlin.idea.core.script.ScriptDefinitionsManagerKt.loadDefinitionsFromTemplates$default(ScriptDefinitionsManager.kt:229)
	at org.jetbrains.kotlin.idea.script.BridgeScriptDefinitionsContributor.getDefinitions(BridgeDefinitionsContributor.kt:30)
	at org.jetbrains.kotlin.idea.core.script.ScriptDefinitionsManager.safeGetDefinitions(ScriptDefinitionsManager.kt:201)
	at org.jetbrains.kotlin.idea.core.script.ScriptDefinitionsManager.reloadScriptDefinitions(ScriptDefinitionsManager.kt:130)
	at org.jetbrains.kotlin.idea.core.script.ScriptDefinitionsManager.getCurrentDefinitions(ScriptDefinitionsManager.kt:116)
	at org.jetbrains.kotlin.scripting.shared.definitions.LazyScriptDefinitionProvider.getCachedDefinitions(LazyScriptDefinitionProvider.kt:27)
	at org.jetbrains.kotlin.scripting.shared.definitions.LazyScriptDefinitionProvider.findScriptDefinition(LazyScriptDefinitionProvider.kt:45)
	at org.jetbrains.kotlin.idea.core.script.ScriptDefinitionsManager.findScriptDefinition(ScriptDefinitionsManager.kt:84)
	at org.jetbrains.kotlin.script.KotlinScriptDefinitionProviderKt.scriptDefinitionByFileName(KotlinScriptDefinitionProvider.kt:65)
	at org.jetbrains.kotlin.script.KotlinScriptDefinitionProviderKt.scriptDefinition(KotlinScriptDefinitionProvider.kt:48)
	at org.jetbrains.kotlin.idea.project.TargetPlatformDetector.getPlatform(TargetPlatformDetector.java:65)
	at org.jetbrains.uast.kotlin.internal.IdeaKotlinUastResolveProviderService.isJvmElement(IdeaKotlinUastResolveProviderService.kt:55)
	at org.jetbrains.uast.kotlin.KotlinUastLanguagePlugin.isJvmElement(KotlinUastLanguagePlugin.kt:77)
	at org.jetbrains.uast.kotlin.KotlinUastLanguagePlugin.convertElementWithParent(KotlinUastLanguagePlugin.kt:86)
	at org.jetbrains.uast.UastFacade.convertElementWithParent(UastContext.kt:80)
	at org.jetbrains.uast.UastContextKt.toUElement(UastContext.kt:127)
	at com.intellij.psi.UastReferenceRegistrar$getOrCreateCachedElement$1.invoke(UastReferenceRegistrar.kt:84)
	at com.intellij.psi.UastReferenceRegistrar$getOrCreateCachedElement$1.invoke(UastReferenceRegistrar.kt)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:129)
	at com.intellij.psi.UastReferenceRegistrar.getOrCreateCachedElement(UastReferenceRegistrar.kt:85)
	at com.intellij.psi.UastReferenceRegistrar.access$getOrCreateCachedElement(UastReferenceRegistrar.kt:1)
	at com.intellij.psi.UastPatternAdapter$accepts$1.compute(UastReferenceRegistrar.kt:111)
	at com.intellij.psi.UastPatternAdapter$accepts$1.compute(UastReferenceRegistrar.kt:102)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.psi.UastPatternAdapter.accepts(UastReferenceRegistrar.kt:110)
	at com.intellij.patterns.PatternConditionPlus.process(PatternConditionPlus.java:47)
	at com.intellij.patterns.PatternConditionPlus.process(PatternConditionPlus.java:26)
	at com.intellij.patterns.ObjectPattern$2.processValues(ObjectPattern.java:104)
	at com.intellij.patterns.PatternConditionPlus.accepts(PatternConditionPlus.java:42)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:61)
	at com.intellij.psi.impl.source.resolve.reference.NamedObjectProviderBinding.addMatchingProviders(NamedObjectProviderBinding.java:114)
	at com.intellij.psi.impl.source.resolve.reference.SimpleProviderBinding.addAcceptableReferenceProviders(SimpleProviderBinding.java:41)
	at com.intellij.psi.impl.source.resolve.reference.PsiReferenceRegistrarImpl.getPairsByElement(PsiReferenceRegistrarImpl.java:129)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:103)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:56)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:55)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:47)
	at com.intellij.psi.impl.source.tree.PsiCoreCommentImpl.getReferences(PsiCoreCommentImpl.java:51)
	at com.intellij.psi.PsiReferenceServiceImpl.doGetReferences(PsiReferenceServiceImpl.java:35)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:22)
	at com.intellij.psi.impl.search.MethodTextOccurrenceProcessor.processTextOccurrence(MethodTextOccurrenceProcessor.java:32)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.lambda$execute$0(PsiSearchHelperImpl.java:770)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:104)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:185)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:143)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processInjectedFile(LowLevelSearchUtil.java:53)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:99)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:185)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.execute(PsiSearchHelperImpl.java:766)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:228)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:219)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:935)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processCandidates$14(PsiSearchHelperImpl.java:726)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$6(PsiSearchHelperImpl.java:413)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
	at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:26)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:397)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$2(PsiSearchHelperImpl.java:302)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$null$3(PsiSearchHelperImpl.java:359)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:208)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$4(PsiSearchHelperImpl.java:358)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1109)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:593)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:539)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:99)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by dkandalov** [comment]
Thanks a lot for noticing the warning!

I think it was caused by classloader namespacing issue when first **liveplugin classloader** loaded `LivePluginAppComponent` class and initialised its companion object, then **kotlin plugin classloader** loaded `LivePluginScriptCompilationConfiguration` which refers to `LivePluginAppComponent` and initialised its companion object again.
